#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']

product:
    path: /products/{id}
    controller: App\Controller\PostProductController::deleteProduct
    methods: ['DELETE']
