#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:       /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

GetCurrentUser:
    path: /me
    controller: App\Controller\GetCurrentUser::getCurrentUser
    methods: ['GET']
